apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: deploystack
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: deploystack-strip-api@kubernetescrd
spec:
  rules:
    - host: deploystack.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
