apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: deploystack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: deploystack-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg://deploystack:deploystack@postgres:5432/deploystack
