apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: deploystack
type: Opaque
stringData:
  POSTGRES_DB: deploystack
  POSTGRES_USER: deploystack
  POSTGRES_PASSWORD: deploystack
